default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :crashlytics do
    gradle(task: "clean :app:store:assembleRelease")
    crashlytics
  end

  desc "Deploy a beta version to the Google Play"
  lane :beta do
    gradle(task: "clean :app:store:bundle")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean :app:store:bundle")
    upload_to_play_store
  end

  desc "Build new version"
  lane :build do
    gradle(task: "clean :app:store:bundle")
  end
end
