name: Android CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.jks.asc > keystore.jks

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Configure Keystore
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        run: |
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties

      - name: Cache GradleCache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradleCache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-gradleCache-${{ hashFiles('**/*.gradle*') }}
            ${{ runner.os }}-gradle-gradleCache-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-gradleWrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-gradle-gradleWrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
            ${{ runner.os }}-gradle-gradleWrapper-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: gradle
          key: ${{ runner.os }}-gradle-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
            ${{ runner.os }}-gradle-gradle-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build  --full-stacktrace

      - name: Junit tests with Gradle
        run: ./gradlew testDebugUnitTest --full-stacktrace

      - name: Cache Gradle
        run: |
          cat **/build/test-results/**/*.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/build/test-results/test*.xml
            **/build/test-results/**/*.xml
          commit: ${{ github.event.pull_request.head.sha || github.sha }}