name: Android Version Update

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy_beta:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Update Version
        run: bash ./.github/scripts/update_versions.sh

      - name: Generate changelog and tag (release)
        id: changelog
        env:
          TAG_PREFIX: release-
        run: ./.github/scripts/generate_changelog.sh

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add fastlane/metadata/android
          git commit -m "release: v${{ steps.changelog.outputs.VERSION_NAME }} (code ${{ steps.changelog.outputs.VERSION_CODE }})"
          # Create an annotated tag for this release
          TAG_NAME="${{ steps.changelog.outputs.TAG_NAME }}"
          if [ -n "$TAG_NAME" ]; then
            # Avoid failure if tag already exists in repo history
            if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "Tag $TAG_NAME already exists; skipping create"
            else
              git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
            fi
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.ref }}
          tags: true